import type { Metadata } from "next";
import Link from "next/link";
import { DIMENSIONS, RUBRIC_VERSION, type DimensionId } from "@/lib/rubric/types";
import { absoluteUrl } from "@/lib/site";

export const metadata: Metadata = {
  title: "Methodology — how the agent-readiness score is measured",
  description:
    "How Qomvia measures agent readiness: six categories, scored from public HTTP responses only. No forms, no purchases, no language-model guesswork.",
  alternates: { canonical: absoluteUrl("/methodology") },
};

const DIMENSION_NOTES: Record<DimensionId, string> = {
  access: "Whether an AI crawler is allowed in at all, and whether the page it receives contains your content.",
  data: "Whether products, prices, availability and identifiers are readable without rendering JavaScript.",
  protocols: "Whether the machine surfaces agents look for exist: feeds, llms.txt, MCP discovery, agentic checkout.",
  checkout: "Whether an agent can get from a product to a payable checkout without an account or a human.",
  performance: "Whether pages answer fast and light enough to be fetched and re-fetched by a bot.",
  policy: "Whether your terms for automated access and a machine-readable contact are published.",
};

export default function MethodologyPage() {
  return (
    <div className="space-y-12">
      <header className="space-y-3 border-b border-rule pb-6">
        <p className="eyebrow">Rubric v{RUBRIC_VERSION}</p>
        <h1 className="font-serif text-4xl tracking-tight">Methodology</h1>
        <p className="max-w-2xl leading-relaxed text-muted">
          Every score is measured from public HTTP responses. Nothing is estimated, bought from a third-party dataset or
          generated by a language model.
        </p>
      </header>

      <section className="space-y-3 border-y border-rule bg-raised px-6 py-6">
        <h2 className="text-xl">What the crawler does and does not do</h2>
        <ul className="list-disc space-y-1 pl-5 text-sm leading-relaxed text-muted">
          <li>Identifies itself as <code className="text-foreground">QomviaBot/1.0</code> with a link to this page.</li>
          <li>Issues only GET requests: roughly 20 for a public scan.</li>
          <li>Never submits a form, never adds to a cart, never attempts a purchase.</li>
          <li>Never tries to defeat a CAPTCHA or bot challenge — a challenge is recorded as a finding and nothing more.</li>
          <li>Respects <code className="text-foreground">robots.txt</code> for every request beyond the homepage and robots file itself.</li>
          <li>Rate-limits to one request per host at a time and caps each response at 2 MB.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <div className="flex flex-wrap items-baseline justify-between gap-3 border-b border-rule pb-2">
          <h2 className="text-2xl">What we score</h2>
          <p className="text-xs text-muted">Six categories, 21 checks, one 0–100 score</p>
        </div>
        <dl className="grid gap-x-10 gap-y-6 sm:grid-cols-2">
          {(Object.keys(DIMENSIONS) as DimensionId[]).map((dimensionId) => (
            <div key={dimensionId} className="border-t border-border pt-3">
              <dt className="text-base">{DIMENSIONS[dimensionId].label}</dt>
              <dd className="mt-1 text-sm leading-relaxed text-muted">{DIMENSION_NOTES[dimensionId]}</dd>
            </div>
          ))}
        </dl>
        <p className="text-sm leading-relaxed text-muted">
          The signal-by-signal rubric, with the measurement behind every check, is in your{" "}
          <Link href="/methodology/signals" className="link-underline">
            account
          </Link>
          .
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="border-b border-rule pb-2 text-2xl">Grades</h2>
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border text-left">
              <th className="eyebrow w-12 py-2 font-normal">Grade</th>
              <th className="eyebrow w-24 py-2 font-normal">Score</th>
              <th className="eyebrow py-2 font-normal">What it means for an agent</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {[
              ["A", "90–100", "Finds, reads and reaches checkout without special handling."],
              ["B", "75–89", "Usable, with gaps that cost you in comparisons."],
              ["C", "60–74", "Can read you, but will struggle to transact."],
              ["D", "40–59", "Significant blockers; most agent journeys fail."],
              ["F", "below 40", "Effectively invisible or closed to agents."],
            ].map(([grade, range, meaning]) => (
              <tr key={grade}>
                <td className="py-2.5 font-serif text-lg">{grade}</td>
                <td className="tabular py-2.5 text-muted">{range}</td>
                <td className="py-2.5 leading-relaxed text-muted">{meaning}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section id="corrections" className="space-y-3 border-y border-rule bg-raised px-6 py-6">
        <h2 className="text-xl">Corrections and re-scans</h2>
        <p className="text-sm leading-relaxed text-muted">
          A score is a snapshot of what our crawler received at a point in time. If you believe a measurement is wrong,
          email corrections@qomvia.com and we will re-run and publish the result. Store owners can remove their public
          page entirely on the{" "}
          <Link href="/opt-out" className="link-underline">
            opt-out page
          </Link>
          .
        </p>
      </section>
    </div>
  );
}
