import type { Metadata } from "next";
import Link from "next/link";
import { SIGNALS } from "@/lib/rubric/signals";
import { DIMENSIONS, RUBRIC_VERSION, type DimensionId } from "@/lib/rubric/types";
import { absoluteUrl, SITE_NAME } from "@/lib/site";

export const metadata: Metadata = {
  title: "Methodology — how the agent-readiness score is measured",
  description:
    "The full rubric: 21 signals across machine access, product data, agent-commerce protocols, checkout traversability, performance and policy. Measured from public HTTP responses only.",
  alternates: { canonical: absoluteUrl("/methodology") },
};

export default function MethodologyPage() {
  return (
    <div className="space-y-12">
      <header className="space-y-3">
        <h1 className="text-3xl font-semibold tracking-tight">Methodology</h1>
        <p className="max-w-2xl text-muted">
          Rubric v{RUBRIC_VERSION}. Every score is the sum of {SIGNALS.length} independently measured signals, each
          worth a fixed number of points. Nothing is estimated, inferred from a third-party dataset, or generated by a
          language model.
        </p>
      </header>

      <section className="space-y-3 rounded-xl border border-border bg-surface p-5">
        <h2 className="font-semibold">What the crawler does and does not do</h2>
        <ul className="list-disc space-y-1 pl-5 text-sm text-muted">
          <li>Identifies itself as <code className="text-foreground">QomviaBot/1.0</code> with a link to this page.</li>
          <li>Issues only GET requests: roughly 20 for a public scan, up to 500 for a paid deep audit.</li>
          <li>Never submits a form, never adds to a cart, never attempts a purchase.</li>
          <li>Never tries to defeat a CAPTCHA or bot challenge — a challenge is recorded as a finding and nothing more.</li>
          <li>Respects <code className="text-foreground">robots.txt</code> for every request beyond the homepage and robots file itself.</li>
          <li>Rate-limits to one request per host at a time and caps each response at 2 MB.</li>
        </ul>
      </section>

      <section className="space-y-8">
        <div className="flex items-baseline justify-between">
          <h2 className="text-xl font-semibold">The rubric</h2>
          <span className="font-mono text-xs text-muted">100 points</span>
        </div>
        {(Object.keys(DIMENSIONS) as DimensionId[]).map((dimensionId) => (
          <div key={dimensionId} className="space-y-3">
            <h3 className="font-medium">
              {DIMENSIONS[dimensionId].label}{" "}
              <span className="font-mono text-xs text-muted">{DIMENSIONS[dimensionId].max} pts</span>
            </h3>
            <div className="overflow-hidden rounded-xl border border-border">
              <ul className="divide-y divide-border">
                {SIGNALS.filter((signal) => signal.dimension === dimensionId).map((signal) => (
                  <li key={signal.id} className="space-y-1 bg-surface px-4 py-3">
                    <div className="flex items-baseline justify-between gap-3">
                      <span className="font-medium">{signal.title}</span>
                      <span className="font-mono text-xs text-muted">{signal.max} pts</span>
                    </div>
                    <p className="text-sm text-muted">{signal.why}</p>
                    <p className="font-mono text-[11px] text-muted">signal id: {signal.id}</p>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        ))}
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">Grades</h2>
        <ul className="text-sm text-muted">
          <li>A — 90 to 100: an agent can find, read and reach checkout without special handling.</li>
          <li>B — 75 to 89: usable, with gaps that cost you in comparisons.</li>
          <li>C — 60 to 74: an agent can read you but will struggle to transact.</li>
          <li>D — 40 to 59: significant blockers; most agent journeys fail.</li>
          <li>F — below 40: effectively invisible or closed to agents.</li>
        </ul>
      </section>

      <section id="corrections" className="space-y-3 rounded-xl border border-border bg-surface p-5">
        <h2 className="font-semibold">Corrections and re-scans</h2>
        <p className="text-sm text-muted">
          Scores are a snapshot of what our crawler received at a point in time. Anyone can trigger a free re-scan from
          the homepage once per hour, and every signal shows the measurement behind it so a result can be reproduced with
          curl. If you believe a measurement is wrong, email corrections@qomvia.com with the signal id and we will
          re-run and publish the result. Store owners can remove their public page entirely on the{" "}
          <Link href="/opt-out" className="text-accent">
            opt-out page
          </Link>
          .
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">Open rubric</h2>
        <p className="text-sm text-muted">
          The rubric and the scoring code are the product of {SITE_NAME}, published so results can be challenged. If a
          signal is unfair or a weight is wrong, we would rather change it than defend it.
        </p>
      </section>
    </div>
  );
}
